title: Alexander Trif
logo: /assets/img/logo.png
description: "Hello! I'm a dedicated Data Analyst in training, with a rich academic background originally rooted in the sciences. My journey began in the realm of Chemistry, where I not only honed my analytical skills but also developed a keen eye for detail and precision. With a minor in Mathematics and Statistics, my enthusiasm for the numerical and theoretical soon guided me towards the intricate world of data analytics."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
