title: Alexander Trif
logo: /assets/img/logo.png
description: I'm a dedicated Data Analyst driven by my passion for mathematics and precision, and I now apply these skills to make a meaningful impact, particularly in the healthcare sector. I find myself enjoying outdoor activities like skiing, mountain biking, and photography.<br><a href='https://www.linkedin.com/in/alex-trif-972450185/' target='_blank'>LinkedIn</a><br><a href='https://www.instagram.com/trif_alexander/'>Instagram</a><br><a href='https://www.youtube.com/@Intermittent-Carb-Lover'>Youtube</a><br><a href='mailto:alextrif25@gmail.com'>Email</a><br><a href='/assets/resume.html'>Resume</a><br><a href='https://www.youtube.com/@Intermittent-Carb-Lover'>Youtube</a> 
theme: jekyll-theme-minimal


