title: Alexander Trif
logo: /assets/img/logo.png
description: I'm a dedicated Data Analyst driven by my passion for mathematics and precision, and I now apply these skills to make a meaningful impact, particularly in the healthcare sector. I find myself enjoying outdoor activities like skiing, mountain biking, and photography.<br><br>lol<br><br><a href='https://www.linkedin.com/in/alex-trif-972450185/' target='_blank'>LinkedIn</a><br><br><a href='https://www.instagram.com/trif_alexander/'>Instagram</a><br><br><a href='https://www.youtube.com/@Intermittent-Carb-Lover'>Youtube</a>
theme: jekyll-theme-minimal
theme: jekyll-theme-minimal
