title: Alexander Trif
logo: /assets/img/logo.png
description: Data Scientist at Metegrity Inc.<br>Machine Learning Pipelines & Production Analytics<br><br><a href='mailto:alextrif25@gmail.com'>Email</a><br><a href='/assets/resume.html'>Resume</a><br><a href='https://www.linkedin.com/in/alex-trif-972450185/' target='_blank'>LinkedIn</a>
theme: jekyll-theme-minimal


